-- Netflix Userbase Analysis Queries
-- This file contains SQL queries designed to derive insights from the Netflix Userbase dataset.


-- Analysis Queries

-- Query 1: Total Number of Users
-- Description: Find the total number of unique users in the dataset.
SELECT COUNT(*) AS total_users
FROM Netflix_Userbase nu;

-- Query 2: Average Monthly Revenue by Subscription Type
-- Description: Calculate the average monthly revenue generated for each subscription type (Basic, Standard, Premium).
SELECT `Subscription Type`, AVG(`Monthly Revenue`) AS avg_monthly_revenue
FROM Netflix_Userbase nu
GROUP BY `Subscription Type`;

-- Query 3: Country-wise User Distribution
-- Description: Determine the number of users from each country to identify key markets.
SELECT Country, COUNT(*) AS user_count
FROM Netflix_Userbase nu
GROUP BY Country
ORDER BY user_count DESC;

-- Query 4: Gender-wise Subscription Type Analysis
-- Description: Count the number of male and female users for each subscription type.
SELECT COUNT(*) AS user_count, Gender, `Subscription Type`
FROM Netflix_Userbase nu
GROUP BY Gender, `Subscription Type`
ORDER BY Gender, `Subscription Type`;

-- Query 5: Subscription Retention Analysis
-- Description: Calculate the difference between `Last Payment Date` and `Join Date` to analyze how long users have stayed subscribed.
SELECT 
    `User ID`,
    DATEDIFF(`Last Payment Date`, `Join Date`) AS subscription_duration_days
FROM Netflix_Userbase nu
ORDER BY subscription_duration_days DESC;

-- Query 6: Age Group Distribution
-- Description: Group users into age ranges (e.g., 18-25, 26-35, 36-45, etc.) and count the number of users in each range.
SELECT 
    CASE 
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    COUNT(*) AS user_count
FROM Netflix_Userbase nu
GROUP BY age_group
ORDER BY age_group;

-- Query 7: Device Preference by Subscription Type
-- Description: Find the most commonly used device for each subscription type.
WITH device_pref AS (
    SELECT 
        Device,
        COUNT(*) AS device_count,
        `Subscription Type`,
        RANK() OVER (PARTITION BY `Subscription Type` ORDER BY COUNT(*) DESC) AS device_rank
    FROM Netflix_Userbase nu
    GROUP BY Device, `Subscription Type`
)
SELECT `Subscription Type`, Device, device_count
FROM device_pref
WHERE device_rank = 1;

-- Query 8: Total Revenue by Country
-- Description: Compute the total revenue generated by users from each country.
SELECT Country, SUM(`Monthly Revenue`) AS total_revenue
FROM Netflix_Userbase nu
GROUP BY Country
ORDER BY total_revenue DESC;

-- Query 9: Users with Long Subscription Durations
-- Description: Identify users who have been subscribed for more than a year.
SELECT `User ID`, DATEDIFF(`Last Payment Date`, `Join Date`) AS subscription_duration_days
FROM Netflix_Userbase nu
WHERE DATEDIFF(`Last Payment Date`, `Join Date`) >= 365
ORDER BY subscription_duration_days DESC;

-- Query 10: Gender-Wise Average Revenue
-- Description: Calculate the average monthly revenue generated by male and female users.
SELECT Gender, AVG(`Monthly Revenue`) AS avg_revenue
FROM Netflix_Userbase nu
GROUP BY Gender
ORDER BY avg_revenue DESC;

-- Query 11: Active vs. Inactive Users
-- Description: Count the number of active and inactive users in the dataset.
SELECT 
    CASE 
        WHEN DATEDIFF(CURDATE(), `Last Payment Date`) <= 30 THEN 'active'
        ELSE 'inactive'
    END AS account_status,
    COUNT(*) AS user_count
FROM Netflix_Userbase nu
GROUP BY account_status;

-- Query 12: High Revenue Generating Users
-- Description: Identify users whose monthly revenue exceeds a certain threshold (e.g., $14).
SELECT `User ID`, `Monthly Revenue`
FROM Netflix_Userbase nu
WHERE `Monthly Revenue` >= 14
ORDER BY `Monthly Revenue` DESC;

-- Query 13: Subscription Popularity by Country
-- Description: Find the most popular subscription type in each country.
WITH sub_pref AS (
    SELECT `Subscription Type`,
        Country,
        COUNT(*) AS subscription_count,
        RANK() OVER (PARTITION BY Country ORDER BY COUNT(*) DESC) AS sub_rank
    FROM Netflix_Userbase nu
    GROUP BY Country, `Subscription Type`
)
SELECT `Subscription Type`, Country, subscription_count
FROM sub_pref
WHERE sub_rank = 1;

-- Query 14: Potential Churn Risk
-- Description: Identify users whose `Last Payment Date` is more than a month old to flag them as potential churn risks.
SELECT 
    CASE 
        WHEN DATEDIFF(CURDATE(), `Last Payment Date`) > 30 THEN 'churn risk'
        ELSE 'not risky'
    END AS account_status,
    `User ID`
FROM Netflix_Userbase nu
GROUP BY account_status, `User ID`;

-- Query 15: Average Subscription Duration by Subscription Type
-- Description: Calculate the average duration (in days) of each subscription type.
SELECT `Subscription Type`, AVG(DATEDIFF(`Last Payment Date`, `Join Date`)) AS avg_duration
FROM Netflix_Userbase nu
GROUP BY `Subscription Type`
ORDER BY avg_duration DESC;

-- Query 16: Total Revenue Across All Users
-- Description: Compute the total revenue generated across the entire dataset.
SELECT SUM(`Monthly Revenue`) AS total_revenue
FROM Netflix_Userbase;

-- Query 17: Correlation Between Age and Monthly Revenue
-- Description: Analyze whether older users tend to subscribe to higher revenue-generating plans.
SELECT 
    CASE 
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS age_group,
    AVG(`Monthly Revenue`) AS avg_monthly_revenue
FROM Netflix_Userbase nu
GROUP BY age_group
ORDER BY avg_monthly_revenue DESC;

-- Query 18: Revenue Growth Opportunity by Country
-- Description: Identify countries with the highest total potential revenue based on the total number of users and their average monthly revenue.
SELECT Country, COUNT(*) AS user_count, AVG(`Monthly Revenue`) AS avg_monthly_revenue, SUM(`Monthly Revenue`) AS total_revenue
FROM Netflix_Userbase nu
GROUP BY Country
ORDER BY total_revenue DESC
LIMIT 3;

-- Query 19: Gender Device Preference
-- Description: Find out which device is most preferred by male and female users.
WITH DevicePref AS (
    SELECT 
        Gender,
        Device,
        COUNT(*) AS device_count,
        RANK() OVER (PARTITION BY Gender ORDER BY COUNT(*) DESC) AS device_rank
    FROM Netflix_Userbase nu
    GROUP BY Gender, Device
)
SELECT Gender, Device, device_count
FROM DevicePref
WHERE device_rank = 1;

-- Query 20: Peak Join Dates
-- Description: Identify the month(s) with the highest number of user registrations.
SELECT MONTH(`Join Date`) AS month_, COUNT(*) AS user_count
FROM Netflix_Userbase nu
GROUP BY month_
ORDER BY user_count DESC
LIMIT 3;


